spring:
  application:
    name: cache-aside
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: "Redis2019!"
    database: 0
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    user: user
    password: password
    url: jdbc:postgresql://localhost:5432/mydatabase